# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-12 11:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 12, 11, 44, 38, 111000, tzinfo = utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
