# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20161013_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=b'', width_field='width'),
        ),
    ]
