# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_auto_20161013_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='height',
            field=models.IntegerField(default=640),
        ),
        migrations.AlterField(
            model_name='post',
            name='width',
            field=models.IntegerField(default=640),
        ),
    ]
